### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by Itislesley** [MatoYing/TextMining#1]
想问下博主方便分享一下数据集吗~想尝试分析学习一下

**Comment by MatoYing** [comment]
CSDN上回复你了，抱歉这个不太方便，这几条应该是够用来学习了。

**Comment by Itislesley** [comment]
哦哦了解了 还是感谢回复哇！



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月03日 13:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MatoYing/TextMining] about data (Issue #1) |

CSDN上回复你了，抱歉这个不太方便，这几条应该是够用来学习了。
